### ISSUE TITLE
Securify issues

### ISSUE THREAD

**Issue by cg505** [frc461/website-2013#3]
See commit a5a4614b45

**Comment by cg505** [comment]
Ha, commit # has 461 in it...

**Comment by rye** [comment]
I'm guessing the best thing to do here would be to jump up a directory and make a new one for this, then redownload team461WBI/website, and then `rake db:migrate`, and follow the README to reset it up. Something's probably screwed up.

Did you install Rails using RVM or did you install it from your repositories? Because if you installed it from your repositories, it could also be out of date.

**Comment by cg505** [comment]
No, still is an issue.

**Comment by braddoeswebdev** [comment]
I played around with it & had issues too.  The problem is the securify method in app/models/permission.rb.  It handles the specific page/post/photo/whatever case fine, but if you try to create a generic permission it fails.

**Comment by cg505** [comment]
Aparrently the model never gets saved. Credit to @btgeek

**Comment by rye** [comment]
Never "gets" saved or never "got" saved?

**Comment by braddoeswebdev** [comment]
Gets - there was no website working this evening.  Show up at lunch tomorrow & we'll see about fixing it.

**Comment by rye** [comment]
Yeah.

**Comment by braddoeswebdev** [comment]
Hold on, I goofed.  Since securify is set up to run before the model saves, we don't have to call save in the method.  It's really a much simpler issue - somebody forgot to actually set securable_type anywhere.

**Comment by cg505** [comment]
No, it's something else that we don't know about...

**Comment by braddoeswebdev** [comment]
Now I know what it is.  And I learned something!  http://stackoverflow.com/questions/5183664/why-isnt-self-always-needed-in-ruby-rails-activerecord
